from __future__ import annotations

from typing import Protocol


class Broker(Protocol):
    def get_cash(self) -> float: ...

    def get_positions(self) -> dict[str, int]: ...

    def get_avg_entry_prices(self) -> dict[str, float]: ...

    def get_price(self, symbol: str) -> float: ...

    def place_order(self, symbol: str, side: str, qty: int) -> None: ...

    def list_open_orders(
        self,
        symbol: str | None = None,
        side: str | None = None,
    ) -> list[dict[str, str]]: ...

    def has_open_order(self, symbol: str, side: str) -> bool: ...

    def is_market_open(self) -> bool: ...
